# Generated by Django 3.1.4 on 2020-12-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlescoreform',
            name='score_5',
            field=models.IntegerField(default=0),
        ),
    ]
