# Generated by Django 3.1.4 on 2020-12-23 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_singlescoreform_score_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlescoreform',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
