# Generated by Django 3.1.4 on 2020-12-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_examiner_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examiner',
            old_name='room',
            new_name='room_id',
        ),
    ]
