# Generated by Django 3.1.4 on 2020-12-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201229_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlescoreform',
            name='score_1',
        ),
        migrations.RemoveField(
            model_name='singlescoreform',
            name='score_2',
        ),
        migrations.RemoveField(
            model_name='singlescoreform',
            name='score_3',
        ),
        migrations.RemoveField(
            model_name='singlescoreform',
            name='score_4',
        ),
        migrations.RemoveField(
            model_name='singlescoreform',
            name='score_5',
        ),
        migrations.AddField(
            model_name='examiner',
            name='is_examiner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='room_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='singlescoreform',
            name='formFinished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singlescoreform',
            name='score',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
